---
driver:
  name: dokken
  chef_version: latest
  privileged: true  # because Docker and systemd/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default

platforms:
- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd

- name: ubuntu-20.04
  driver:
    image: dokken/ubuntu-20.04
    pid_one_command: /bin/systemd

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd

- name: debian-10
  driver:
    image: dokken/debian-10
    pid_one_command: /bin/systemd

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: centos-8
  driver:
    image: dokken/centos-8
    pid_one_command: /usr/lib/systemd/systemd

suites:
- name: default
  run_list:
    - recipe[golang_test::default]
- name: src
  run_list:
    - recipe[golang_test::default]
  attributes:
    golang:
      from_source: true
      arch: 'amd64'
