---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-16.04
- name: debian-8
- name: centos-6.9

suites:
- name: default
  run_list:
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes:
    golang:
      owner: 'vagrant'
      group: 'vagrant'
- name: src
  run_list:
    - recipe[golang_test::default]
    - recipe[minitest-handler]
  attributes:
    golang:
      from_source: true
      arch: 'amd64'
      owner: 'vagrant'
      group: 'vagrant'
